name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Make directory for SSH key
        run: mkdir -p ~/.ssh_myhmm_client

      - name: Save secret SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh_myhmm_client/id_rsa_myhmm_client
        shell: bash

      - name: Set permissions for SSH key
        run: chmod 600 ~/.ssh_myhmm_client/id_rsa_myhmm_client

      - name: Generate .env.local locally
        run: |
          cat > .env.local <<EOL
          AUTH_SECRET=${{ secrets.AUTH_SECRET }}
          SESSION_MAX_AGE=${{ secrets.SESSION_MAX_AGE }}
          API_URL=http://108.136.179.201:2212/api/v1
          BLOB_READ_WRITE_TOKEN=${{ secrets.BLOB_READ_WRITE_TOKEN }}
          YOUTUBE_API_SECRET_KEY=${{ secrets.YOUTUBE_API_SECRET_KEY }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOL

      - name: Copy .env.local to EC2
        run: |
          scp -i ~/.ssh_myhmm_client/id_rsa_myhmm_client \
              -o StrictHostKeyChecking=no \
              .env.local ec2-user@108.136.179.201:/home/ec2-user/pwa-hmm-frontend/.env.local

      - name: Pull repository
        run: |
          ssh -i ~/.ssh_myhmm_client/id_rsa_myhmm_client \
              -o StrictHostKeyChecking=no \
              ec2-user@108.136.179.201 <<'EOF'
          
            APP_DIR="/home/ec2-user/pwa-hmm-frontend"
            cd "$APP_DIR"
          
            if [ ! -d ".git" ]; then
              git clone https://github.com/jhoniananta/pwa-hmm-frontend.git .
            else
              git reset --hard
              git fetch
            fi
          
            git checkout staging
            git pull origin staging
          EOF

      - name: Install dependencies
        run: npm install --production

      - name: Build application
        run: npm run build

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-southeast-3

      - name: Create tar.gz of build folder
        run: |
          tar -czf build.tar.gz .next public 

      - name: Upload to S3
        run: |
          aws s3 cp build.tar.gz s3://myhmm-bucket/deploy/build.tar.gz --acl public-read

      - name: SSH into EC2 and download from S3
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@108.136.179.201 <<'EOF'
            cd /home/ec2-user/pwa-hmm-frontend
            aws s3 cp s3://myhmm-bucket/deploy/build.tar.gz .
            tar -xzf build.tar.gz
          EOF

      - name: Deploy to EC2 (via SSH as ec2-user)
        run: |
          ssh -i ~/.ssh_myhmm_client/id_rsa_myhmm_client \
              -o StrictHostKeyChecking=no \
              ec2-user@108.136.179.201 <<'EOF'
          
            pm2 stop myhmm_client | true
            pm2 delete myhmm_client | true
            pm2 restart ecosystem.config.js
          EOF
